music = {
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "shapeofyou": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "faded": "https://www.youtube.com/watch?v=60ItHLz5WEA",
    "nightchanges": "https://www.youtube.com/watch?v=syFZfO_wfMQ",
    "undertheinfluence": "https://www.youtube.com/watch?v=5GqFiv9FZsA",
    "letmeloveyou": "https://www.youtube.com/watch?v=SMs0GnYze34",
    "calmdown": "https://www.youtube.com/watch?v=WcIcVapfqXw",
    "attention": "https://www.youtube.com/watch?v=nfs8NYg7yQM",
    "blinding lights": "https://www.youtube.com/watch?v=4NRXx6U8ABQ",
    "seeyouagain": "https://www.youtube.com/watch?v=RgKAFK5djSk",
    "lovemelikeyoudo": "https://www.youtube.com/watch?v=AJtDXIazrMo",
    "closer": "https://www.youtube.com/watch?v=PT2_F-1esPk",
    "memories": "https://www.youtube.com/watch?v=SlPhMPnQ58k",
    "photograph": "https://www.youtube.com/watch?v=SPKBtZHuzKY",
    "stay": "https://www.youtube.com/watch?v=kTJczUoc26U",
    "heatwaves": "https://www.youtube.com/watch?v=mRD0-GxqHVo",
    "someoneyouloved": "https://www.youtube.com/watch?v=bCuhuePlP8o",
    "untilIfoundyou": "https://www.youtube.com/watch?v=Ec92Wa0VkxA",
    "unstoppable": "https://www.youtube.com/watch?v=YaEG2aWJnZ8",
    "calmdown": "https://www.youtube.com/watch?v=WcIcVapfqXw",
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    "letmeloveyou": "https://www.youtube.com/watch?v=SMs0GnYze34",
    "nightchanges": "https://www.youtube.com/watch?v=syFZfO_wfMQ",
    "undertheinfluence": "https://www.youtube.com/watch?v=5GqFiv9FZsA",
    "believer": "https://www.youtube.com/watch?v=7wtfhZwyrcc",
    "faded": "https://www.youtube.com/watch?v=60ItHLz5WEA",
    "shape of you": "https://www.youtube.com/watch?v=JGwWNGJdvx8",
    "pushpa": "https://www.youtube.com/watch?v=kN6HHzEXKFU&list=RDkN6HHzEXKFU&start_radio=1",
    "hunter": "https://www.youtube.com/watch?v=Qds5tztmb5g&list=RDkN6HHzEXKFU&index=2",
    "apt": "https://www.youtube.com/watch?v=ZYJpHwGjls4",
    "alameyo": "https://www.youtube.com/watch?v=OGNtViD4QZA",
    "ramsiyaram": "https://www.youtube.com/watch?v=K5KAc5CoCuk",
    "kesariya": "https://www.youtube.com/watch?v=BddP6PYo2gs",
    "apnabanale": "https://www.youtube.com/watch?v=qtZJuEJhekE"
}
